import { zValidator } from '@hono/zod-validator';
import type { Hono } from 'hono';
import { assertFinancialInput, currency, date, expenseInput, scheduledExpenseInput, scheduledExpenseStatusInput, settlementInput, transactionVersionInput } from '../shared/schemas';
import { assertLikeSearch, Repository, RepositoryError } from '../db/repository';

type RouteHelpers = {
  authorizedGroup: (c: any, groupId: string) => Promise<any>;
  authorizedScheduled: (c: any, scheduledId: string) => Promise<any>;
  getRepo: (c: any) => Repository;
  jsonError: (c: any, status: number, code: string, message: string, details?: Record<string, unknown>) => Response;
  repositoryError: (c: any, error: unknown) => Response;
  balanceError: (c: any, error: unknown) => Response | undefined;
  validPeople: (repo: Repository, groupId: string, ids: string[]) => Promise<boolean>;
  page: (value: string | undefined, fallback: number, max: number) => number;
  rejectOffset: (c: any) => Response | undefined;
};

const auth = (c: any) => c.get('auth') as { id: string };

/** Register the ledger's expense, scheduled-expense, and settlement routes.
 * Middleware remains owned by the Worker and this function only receives the
 * authorization/data helpers needed to preserve the existing API contract. */
export function registerExpenseSettlementRoutes(api: Hono<any>, helpers: RouteHelpers) {
  const { authorizedGroup, authorizedScheduled, getRepo, jsonError, repositoryError, balanceError, validPeople, page, rejectOffset } = helpers;

  api.get('/api/groups/:groupId/expenses', async (c) => { const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x; const offsetError = rejectOffset(c); if (offsetError) return offsetError; const q = c.req.query(); const limit = page(q.limit, 50, 100); if (limit < 1) return jsonError(c, 400, 'INVALID_PAGINATION', 'Pagination values must be finite non-negative integers'); try { if (q.from) date.parse(q.from); if (q.to) date.parse(q.to); assertLikeSearch(q.q); } catch (error) { if (error instanceof RepositoryError) return repositoryError(c, error); return jsonError(c, 400, 'INVALID_DATE', 'Date filters must be real YYYY-MM-DD dates'); } try { const result = await x.repo.expensePage(c.req.param('groupId'), { q: q.q, person: q.person, category: q.category, from: q.from, to: q.to, currency: q.currency, limit, cursor: q.cursor }); return c.json({ expenses: result.items, nextCursor: result.nextCursor }); } catch (error) { return repositoryError(c, error); } });
  api.get('/api/groups/:groupId/transactions', async (c) => {
    const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x;
    const offsetError = rejectOffset(c); if (offsetError) return offsetError;
    const q = c.req.query(), limit = page(q.limit, 25, 100);
    if (limit < 1) return jsonError(c, 400, 'INVALID_PAGINATION', 'Pagination values must be finite non-negative integers');
    if (q.kind !== undefined && q.kind !== 'expense' && q.kind !== 'settlement') return jsonError(c, 400, 'INVALID_FILTER', 'Transaction kind must be expense or settlement');
    if (q.currency !== undefined && !currency.safeParse(q.currency).success) return jsonError(c, 400, 'INVALID_FILTER', 'Currency filter is invalid');
    try { if (q.from) date.parse(q.from); if (q.to) date.parse(q.to); assertLikeSearch(q.q); } catch (error) { if (error instanceof RepositoryError) return repositoryError(c, error); return jsonError(c, 400, 'INVALID_DATE', 'Date filters must be real YYYY-MM-DD dates'); }
    try {
      const result = await x.repo.transactionPage(c.req.param('groupId'), { kind: q.kind as 'expense' | 'settlement' | undefined, q: q.q, person: q.person, category: q.category, from: q.from, to: q.to, currency: q.currency, limit, cursor: q.cursor });
      return c.json({ transactions: result.items, nextCursor: result.nextCursor });
    } catch (error) { return repositoryError(c, error); }
  });
  api.get('/api/groups/:groupId/scheduled-expenses', async (c) => { const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x; const q = c.req.query(); const limit = page(q.limit, 100, 100); const offset = q.offset === undefined ? undefined : page(q.offset, 0, Number.MAX_SAFE_INTEGER); if (limit < 1 || (offset !== undefined && offset < 0) || (q.cursor && q.offset !== undefined)) return jsonError(c, 400, 'INVALID_PAGINATION', q.cursor && q.offset !== undefined ? 'Use either cursor or offset pagination' : 'Pagination values must be finite non-negative integers'); try { const result = await x.repo.scheduledExpenses(c.req.param('groupId'), { limit, offset, cursor: q.cursor }); return c.json({ scheduledExpenses: result.items, nextCursor: result.nextCursor }); } catch (error) { return repositoryError(c, error); } });
  api.post('/api/groups/:groupId/scheduled-expenses', zValidator('json', scheduledExpenseInput), async (c) => {
    const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x;
    const input = c.req.valid('json');
    try { assertFinancialInput({ ...input, date: input.start_date }); } catch (error) { const balanceResponse = balanceError(c, error); if (balanceResponse) return balanceResponse; return jsonError(c, 400, 'INVALID_FINANCIAL_INPUT', error instanceof Error ? error.message : 'Invalid financial input'); }
    if (!(await validPeople(x.repo, c.req.param('groupId'), [...input.payers, ...input.splits].map((person) => person.person_id)))) return jsonError(c, 400, 'INVALID_MEMBER', 'Every payer and split must be a group member');
    try { return c.json({ scheduledExpense: await x.repo.createScheduledExpense(c.req.param('groupId'), x.auth.id, input) }, 201); } catch (error) { return repositoryError(c, error); }
  });
  api.post('/api/groups/:groupId/expenses', zValidator('json', expenseInput), async (c) => { const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x; const input = c.req.valid('json'); try { assertFinancialInput(input); } catch (error) { const balanceResponse = balanceError(c, error); if (balanceResponse) return balanceResponse; return jsonError(c, 400, 'INVALID_FINANCIAL_INPUT', error instanceof Error ? error.message : 'Invalid financial input'); } try { if (!(await validPeople(x.repo, c.req.param('groupId'), [...input.payers, ...input.splits].map((p) => p.person_id))) ) return jsonError(c, 400, 'INVALID_MEMBER', 'Every payer and split must be a group member'); return c.json({ expense: await x.repo.createExpense(c.req.param('groupId'), x.auth.id, input) }, 201); } catch (error) { return repositoryError(c, error); } });
  api.put('/api/scheduled-expenses/:scheduledExpenseId', zValidator('json', scheduledExpenseInput), async (c) => {
    const x = await authorizedScheduled(c, c.req.param('scheduledExpenseId')); if (x instanceof Response) return x;
    const input = c.req.valid('json');
    try { assertFinancialInput({ ...input, date: input.start_date }); } catch (error) { const balanceResponse = balanceError(c, error); if (balanceResponse) return balanceResponse; return jsonError(c, 400, 'INVALID_FINANCIAL_INPUT', error instanceof Error ? error.message : 'Invalid financial input'); }
    if (!(await validPeople(x.repo, x.scheduled.groupId, [...input.payers, ...input.splits].map((person) => person.person_id)))) return jsonError(c, 400, 'INVALID_MEMBER', 'Every payer and split must be a group member');
    try { return c.json({ scheduledExpense: await x.repo.updateScheduledExpense(c.req.param('scheduledExpenseId'), x.auth.id, input) }); } catch (error) { return repositoryError(c, error); }
  });
  api.get('/api/scheduled-expenses/:scheduledExpenseId', async (c) => { const x = await authorizedScheduled(c, c.req.param('scheduledExpenseId')); if (x instanceof Response) return x; return c.json({ scheduledExpense: x.scheduled }); });
  for (const [action, method] of [['pause', 'pauseScheduledExpense'], ['resume', 'resumeScheduledExpense'], ['cancel', 'cancelScheduledExpense'] ] as const) {
    api.post(`/api/scheduled-expenses/:scheduledExpenseId/${action}`, zValidator('json', scheduledExpenseStatusInput), async (c) => {
      const x = await authorizedScheduled(c, c.req.param('scheduledExpenseId')); if (x instanceof Response) return x;
      try { const result = await x.repo[method](c.req.param('scheduledExpenseId'), x.auth.id, c.req.valid('json').version); return c.json({ scheduledExpense: result }); } catch (error) { return repositoryError(c, error); }
    });
  }
  api.get('/api/expenses/:expenseId', async (c) => { const repo = getRepo(c), expense = await repo.expenseForUser(c.req.param('expenseId'), auth(c).id, true); if (!expense || (expense.deletedAt && Date.now() - Date.parse(expense.deletedAt) > 30 * 24 * 60 * 60 * 1000)) return jsonError(c, 404, 'EXPENSE_NOT_FOUND', 'Expense not found'); const x = await authorizedGroup(c, expense.groupId); if (x instanceof Response) return x; return c.json({ expense, history: await x.repo.revisions('expense', c.req.param('expenseId')) }); });
  api.put('/api/expenses/:expenseId', zValidator('json', expenseInput), async (c) => { const repo = getRepo(c), old = await repo.expenseForUser(c.req.param('expenseId'), auth(c).id); if (!old) return jsonError(c, 404, 'EXPENSE_NOT_FOUND', 'Expense not found'); const x = await authorizedGroup(c, old.groupId); if (x instanceof Response) return x; const input = c.req.valid('json'); try { assertFinancialInput(input); } catch (error) { const balanceResponse = balanceError(c, error); if (balanceResponse) return balanceResponse; return jsonError(c, 400, 'INVALID_FINANCIAL_INPUT', error instanceof Error ? error.message : 'Invalid financial input'); } try { if (input.version === undefined) return jsonError(c, 409, 'CONFLICT', 'The loaded record version is required'); if (!(await validPeople(x.repo, old.groupId, [...input.payers, ...input.splits].map((p) => p.person_id)))) return jsonError(c, 400, 'INVALID_MEMBER', 'Every payer and split must be a group member'); const expense = await x.repo.updateExpense(c.req.param('expenseId'), x.auth.id, input); if (!expense) return jsonError(c, 409, 'CONFLICT', 'The record was deleted by another request'); return c.json({ expense }); } catch (error) { return repositoryError(c, error); } });
  api.delete('/api/expenses/:expenseId', async (c) => { const repo = getRepo(c), old = await repo.expenseForUser(c.req.param('expenseId'), auth(c).id); if (!old) return jsonError(c, 404, 'EXPENSE_NOT_FOUND', 'Expense not found'); const x = await authorizedGroup(c, old.groupId); if (x instanceof Response) return x; const version = page(c.req.query('version'), -1, Number.MAX_SAFE_INTEGER); if (version < 1) return jsonError(c, 400, 'INVALID_VERSION', 'A positive record version is required'); try { await x.repo.deleteExpense(c.req.param('expenseId'), x.auth.id, version); return c.body(null, 204); } catch (error) { return repositoryError(c, error); } });
  api.post('/api/expenses/:expenseId/restore', zValidator('json', transactionVersionInput), async (c) => { const repo = getRepo(c), expense = await repo.expenseForUser(c.req.param('expenseId'), auth(c).id, true); if (!expense || !expense.deletedAt || Date.now() - Date.parse(expense.deletedAt) > 30 * 24 * 60 * 60 * 1000) return jsonError(c, 404, 'EXPENSE_NOT_FOUND', 'Deleted expense not found'); const x = await authorizedGroup(c, expense.groupId); if (x instanceof Response) return x; try { return c.json({ expense: await x.repo.restoreExpense(c.req.param('expenseId'), x.auth.id, c.req.valid('json').version) }); } catch (error) { return repositoryError(c, error); } });

  api.get('/api/groups/:groupId/settlements', async (c) => { const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x; const offsetError = rejectOffset(c); if (offsetError) return offsetError; const q = c.req.query(), limit = page(q.limit, 50, 100); if (limit < 1) return jsonError(c, 400, 'INVALID_PAGINATION', 'Pagination values must be finite non-negative integers'); try { const result = await x.repo.settlementPage(c.req.param('groupId'), { limit, cursor: q.cursor }); return c.json({ settlements: result.items, nextCursor: result.nextCursor }); } catch (error) { return repositoryError(c, error); } });
  api.post('/api/groups/:groupId/settlements', zValidator('json', settlementInput), async (c) => { const x = await authorizedGroup(c, c.req.param('groupId')); if (x instanceof Response) return x; const input = c.req.valid('json'), people = await x.repo.groupPeople(c.req.param('groupId')); if (input.from_person_id === input.to_person_id || !people.includes(input.from_person_id) || !people.includes(input.to_person_id)) return jsonError(c, 400, 'INVALID_SETTLEMENT', 'Settlement participants are invalid'); try { return c.json({ settlement: await x.repo.createSettlement(c.req.param('groupId'), x.auth.id, input) }, 201); } catch (error) { return repositoryError(c, error); } });
  api.put('/api/settlements/:settlementId', zValidator('json', settlementInput), async (c) => { const input = c.req.valid('json'), repo = getRepo(c), row = await repo.settlementForUser(c.req.param('settlementId'), auth(c).id); if (!row) return jsonError(c, 404, 'SETTLEMENT_NOT_FOUND', 'Settlement not found'); const x = await authorizedGroup(c, row.groupId); if (x instanceof Response) return x; const people = await repo.groupPeople(row.groupId); if (input.version === undefined || input.from_person_id === input.to_person_id || !people.includes(input.from_person_id) || !people.includes(input.to_person_id)) return jsonError(c, 400, 'INVALID_SETTLEMENT', 'Settlement version or participants are invalid'); try { const settlement = await repo.updateSettlement(c.req.param('settlementId'), x.auth.id, input); if (!settlement) return jsonError(c, 409, 'CONFLICT', 'The record was deleted by another request'); return c.json({ settlement }); } catch (error) { return repositoryError(c, error); } });
  api.delete('/api/settlements/:settlementId', async (c) => { const repo = getRepo(c), row = await repo.settlementForUser(c.req.param('settlementId'), auth(c).id); if (!row) return jsonError(c, 404, 'SETTLEMENT_NOT_FOUND', 'Settlement not found'); const x = await authorizedGroup(c, row.groupId); if (x instanceof Response) return x; const version = page(c.req.query('version'), -1, Number.MAX_SAFE_INTEGER); if (version < 1) return jsonError(c, 400, 'INVALID_VERSION', 'A positive record version is required'); try { await x.repo.deleteSettlement(c.req.param('settlementId'), x.auth.id, version); return c.body(null, 204); } catch (error) { return repositoryError(c, error); } });
  api.get('/api/settlements/:settlementId', async (c) => { const repo = getRepo(c), row = await repo.settlementForUser(c.req.param('settlementId'), auth(c).id, true); if (!row || (row.deletedAt && Date.now() - Date.parse(row.deletedAt) > 30 * 24 * 60 * 60 * 1000)) return jsonError(c, 404, 'SETTLEMENT_NOT_FOUND', 'Settlement not found'); const x = await authorizedGroup(c, row.groupId); if (x instanceof Response) return x; return c.json({ settlement: row, history: await x.repo.revisions('settlement', c.req.param('settlementId')) }); });
  api.post('/api/settlements/:settlementId/restore', zValidator('json', transactionVersionInput), async (c) => { const repo = getRepo(c), row = await repo.settlementForUser(c.req.param('settlementId'), auth(c).id, true); if (!row || !row.deletedAt || Date.now() - Date.parse(row.deletedAt) > 30 * 24 * 60 * 60 * 1000) return jsonError(c, 404, 'SETTLEMENT_NOT_FOUND', 'Deleted settlement not found'); const x = await authorizedGroup(c, row.groupId); if (x instanceof Response) return x; try { return c.json({ settlement: await repo.restoreSettlement(c.req.param('settlementId'), x.auth.id, c.req.valid('json').version) }); } catch (error) { return repositoryError(c, error); } });
}
